### ISSUE TITLE
Can't use it as a dependency for a linux project

### ISSUE THREAD

**Issue by nuscheltier** [alanhoff/rust-webview#1]
Is it possible, that your library requires MacOS to compile? :)
I'd like to test it a bit, but I don't have a Mac to compile it.

**Comment by fschutt** [comment]
Yes, doesn't build on Linux for me either.

```
warning: unused manifest key: package.category
   Compiling webview v0.1.0 (file:///home/felix/Development/rust-webview)
error: failed to run custom build command for `webview v0.1.0 (file:///home/felix/Development/rust-webview)`
process didn't exit successfully: `/home/felix/Development/rust-webview/target/debug/build/webview-2c082a64bd06b875/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=framework=Cocoa
cargo:rustc-link-lib=framework=WebKit
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-x" "objective-c" "-DWEBVIEW_COCOA=1" "-o" "/home/felix/Development/rust-webview/target/debug/build/webview-59ee618302c87f8b/out/library/webview.o" "-c" "library/webview.c"
cargo:warning=cc: error trying to exec 'cc1obj': execvp: Datei oder Verzeichnis nicht gefunden
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-x" "objective-c" "-DWEBVIEW_COCOA=1" "-o" "/home/felix/Development/rust-webview/target/debug/build/webview-59ee618302c87f8b/out/library/webview.o" "-c" "library/webview.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.4/src/lib.rs:1984:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: cc::fail
             at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.4/src/lib.rs:1984
   8: cc::Build::compile
             at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.4/src/lib.rs:875
   9: build_script_build::main
             at ./build.rs:7
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  11: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  12: main
  13: __libc_start_main
  14: _start
```

**Comment by alanhoff** [comment]
I'll add Linux & Windows support this weekend

**Comment by ghost** [comment]
did you added Windows support? just questioning before start using

**Comment by fschutt** [comment]
@DoctorVWA there is a similar library called web-view: https://github.com/Boscop/web-view - you may want to use that, it works on windows

**Comment by ghost** [comment]
I saw it before, but looks like that here is more organizated than the other, I'll wait and see if I'll be able to use this here, if not I can use the other without problems, thanks @fschutt

**Comment by alanhoff** [comment]
Added Windows/Linux support, sorry for the delay
